
DefaultContentLanguage: fr
address: "1 Rue de Croix de Luizet 69100 Villeurbanne"
title: La MYNE

Languages:
  en:
    lang: en
    info: "Public openings on Wednesday from 6PM or through personal contact"
    subtitle: Manufacture of Ideas and New Experiments
    catchline: "A Common based Tiers-Lieu for Transitions - #TILIOS <br><br> A Space for Freedom, Experimentations<br> and Citizen Innovation"
    weight: 2
    newsletter: Follow our Newsletter
    event: "Meet us during:"
    news: Check our last news
    more: More

    menu:
      main:
      - identifier: about
        name: About
        url: /en/about
        weight: 0
      - identifier: program
        name: Program
        url: /en/program/
        weight: 1
      - identifier: projects
        name: Projects
        url: /en/project/
        weight: 2
      - identifier: contribute
        name: Contribute
        url: /en/contribute/
        weight: 3
  #    - identifier: agenda
  #      name: Agenda
  #      url: /en/agenda/
  #      weight: 4
    weight: 1

    mission:
      - title: "A place for Work and Prototyping"
        description: "Creation and experimentation space, la MYNE welcomes you in the Seri[O]us Space for coworking, in the N[O]t So Seri[O]us Space for cotalking, in the Lab[O] for experimenting and in the Atel[I]er for creation, not forgetting the garden for your permaculture desires."
        picto: /img/picto-house.png
        link: /en/program#accompagnement

      - title: "Peer-to-Peer Learning, MeetUp and Sharing"
        description: "Through a peer-to-peer learning approach and free access to either material or immaterial resources, La M[Y]NE members can freely benefit from the meetups, as well as open workshops and masterclasses program. La MYNE is a space for improbable meetups and exchanges times."
        picto: /img/picto-experiment.png
        link: /en/program

      - title: "Appropriation, Contribution and Autonomy"
        description: "As a co-constructed and co-managed space, La MYNE lives by and for the community and projects that compose it. Nurture by transparency, governance as well as business models are open both for auditability and to contribution. Anyone can contribute and learn."
        picto: /img/picto-fork.png
        link: /contribute

    catchlinehero:
      - content: "For and by all.<br>Either experts or not | For Organizations of all types.<br><br>La MYNE and the ecosystem we belong to are reglarly gathering around <br>Workshops - Conference - Camp - Masterclass<br> as well as to come in support and pre-incubation of projects."
        calltoaction: Discover our program
        link: /program

    ecosystem:
      - title: La MYNE and its ecosytem
        content: "The finesse of the local, the strength of the global!<br><br> Because the community of La MYNE is based on new forms of partnerships, collaboration and collective intelligence, it is part of a closely interconnected ecosystem."

  fr:
    lang: fr
    info: 'Ouverture au public le Mercredi à partir de 18h ou contactez-nous'
    subtitle: Manufacture des Idées et des Nouvelles Expérimentations
    catchline: "Tiers-Lieu des Transitions par les communs - #TILIOS<br><br> Un Espace de Liberté, d'Expérimentations<br> et d'Innovation Citoyenne"
    weight: 2
    newsletter: Suivez notre Newsletter
    event: Retrouvez-nous
    news: Dernières Actualités
    more: En Savoir Plus
    menu:
      main:
      - identifier: about
        name: About
        url: /about
        weight: 0
      - identifier: program
        name: Programme
        url: /program/
        weight: 1
      - identifier: projects
        name: Projets
        url: /project/
        weight: 2
      - identifier: contribute
        name: Contribuer
        url: /contribute/
        weight: 3
  #    - identifier: agenda
  #      name: Agenda
  #      url: /agenda/
  #      weight: 4
    mission:
      - title: "Espace de Travail et de Prototypage"
        description: "Espace de création et d'expérimentation, la MYNE vous accueille au Seri[O]us Space pour Coworker, au N[O]t So Seri[O]us Space pour Coparler, au Lab[O] expérimenter et à l'Atel[I]er pour créer, sans oublier le Jardin pour vos envies permacoles. Retrouvez-nous les mercredi soir lors des sessions OX[Y]GEN."
        picto: /img/picto-house.png
        link: /program#accompagnement

      - title: "Apprentissage pair-à-pair, Rencontre et Partage"
        description: "Au travers d'un cadre d'apprentissage pair-à-pair et la mise à disposition de ressources matérielles et immatérielles, tous les membres bénéfécient librement de programmes de recontres et d'ateliers ouverts. La MYNE est un espace de rencontres et d'échanges plus ou moins improbables."
        picto: /img/picto-experiment.png
        link: /program

      - title: "Appropriation, Contribution et Autonomisation"
        description: "Espace co-construit et co-géré, la MYNE vit par et pour la communauté et les projets qui la composent. Nourries par un effort de transparence, les modalités de gouvernance et de développements économiques sont ouvertes. Chacun peut contribuer et apprendre en devenant membre ou en participant aux groupes de travail."
        picto: /img/picto-fork.png
        link: /contribute

    catchlinehero:
      - content: Par tou.te.s, pour tou.te.s et avec chacun. <br>Expert-e-s ou non | Quel que soit votre organisation.<br><br>La MYNE et l'écosystème dans lequel elle s'inscrit se retrouvent régulièrement pour des <br>Ateliers - Conférences - Camps - Masterclasses<br> ainsi que pour venir en support de projets et en pré-incubation.
        calltoaction: Découvrez notre programme
        link: /program

    ecosystem:
      - title: La MYNE et son écosytème
        content: La finesse du local, la force du global !<br><br> Parce que la communauté de la MYNE repose sur de nouveaux modes de partenariat, de collaboration et d’intelligence collective, elle s’inscrit dans un écosystème fortement interconnecté globalement et soudé localement.


SectionPagesMenu:
- main
- citoyen
baseurl: /
canonifyurls: true
config: config.yaml
MetaDataFormat : yaml
params:
  DateForm: Monday, Jan 2
  banner:
    sections:
    - image: /img/project-banner.jpg
      name: Projects
    - image: /img/lamyne-banner.jpg
      name: La MYNE
    - image: /img/contribute-banner.jpg
      name: Contribute
    - image: /img/agenda-banner.jpg
      name: Agendas
    - image: /img/program-banner.jpg
      name: Programs
  partners:
  - link: http://lapaillasse.org/
    logo: /img/paillasse-logo.png
    name: La Paillasse
  - link: http://movilab.org/index.php?title=La_POC_Foundation
    logo: /img/poc-foundation-logo.png
    name: POC Foundation
  - link: https://openara.org/
    logo: /img/open-ara-logo.png
    name: Open Ara
  - link: http://www.cellabz.com/
    logo: /img/cellabz-logo.jpg
    name: Cellabz
  - link: http://www.grandlyon.com/
    logo: /img/grand-lyon-logo.png
    name: 'Grand Lyon '
  - link: https://www.insa-lyon.fr/
    logo: /img/insa-logo.png
    name: INSA Lyon
  - link: http://www.fablab-lyon.fr/
    logo: /img/fol-logo.jpg
    name: La Fabrique d'Objets Libres
  - link: https://labolyon.fr/
    logo: /img/lol-logo.png
    name: Le Laboratoire Ouvert Lyonnais
  - link: http://www.ecam.fr/fr/ecam-lyon/ecam-lyon
    logo: /img/ecam-logo.png
    name: 'ECAM '
  - link: http://ouishare.net/fr
    logo: /img/ouishare-logo.png
    name: Ouishare
  - link: http://www.ens-lyon.fr/
    logo: /img/ens-logo.jpg
    name: ENS Lyon
  - link: http://www.tuba-lyon.com/
    logo: /img/tuba-logo.jpg
    name: TUBA
  social:
  - header: 'yes'
    icon: icon-twitter
    title: twitter
    url: https://twitter.com/laMYNE_
  - header: 'yes'
    icon: icon-github
    title: github
    url: https://github.com/La-MYNE
  - header: 'yes'
    icon: icon-facebook
    title: facebook
    url: https://www.facebook.com/La-MYNE-initi%C3%A9e-par-La-Paillasse-Sa%C3%B4ne-648362331890903/
  - icon: icon-linkedin
    title: linkedin
    url: https://www.linkedin.com/company/la-myne-by-lps-
  - icon: icon-flickr
    title: flickr
    url: https://www.flickr.com/photos/lps_myne/
  - header: 'yes'
    icon: icon-slack
    title: slack
    url: https://la-myne.slack.com
  - header: 'yes'
    icon: icon-mail
    title: email
    url: team@lamyne.org
  - icon: ion-social-youtube-outline
    title: youtube
    url: https://www.youtube.com/channel/UC-AkSeIOQf3-fscKmoXfmxA


taxonomies:
  categorie: categories
  project: projects
  tag: tags
