[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"
  TZ = "Europe/Paris"

[context.deploy-preview]
  command = "yarn build-preview"
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "ALLOW-FROM https://cloud.lamyne.org"
X-XSS-Protection = "1; mode=block"
Access-Control-Allow-Origin= "https://cloud.lamyne.org"
