backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Node", name: "node", widget: "list"}
      - {label: "Tags", name: "tags", widget:"list", require:"false"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image Banner", name: "banner", widget:"image", require:"false"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image", require:"false"}
      - {label: "Description", name: "description", widget:"string"}
      - {label: "Porteurs", name: "porteurs", widget:"list"}
      - {label: "Documentation", name: "documentation", require:"false", widget: list, fields: [
          {label: "Nom", name: "name", widget: "string"},
          {label: "Lien", name: "link", widget: "string"}]}
      - {label: "Contribuer-Competence", name: competence, require:"false", widget: list, fields: [
          {label: "Type", name: "name", widget: "string"},
          {label: "Description", name: "description", widget: "string"}]}
      - {label: "Contribuer-Materiel", require:"false", name: materiel, widget: list, fields: [
          {label: "Type", name: "name", widget: "string"},
          {label: "Description", name: "description", widget: "string"}]}
      - {label: "Contribuer-Financier", require:"false", name: financier, widget: list, fields: [
          {label: "Type", name: "name", widget: "string"},
          {label: "Description", name: "description", widget: "string"}]}
  - name: "ateliers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Atelier et Formation" # Used in the UI, ie.: "New Post"
    folder: "site/content/ateliers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Node", name: "node", widget: "list"}
      - {label: "Tags", name: "tags", widget:"list", require:"false"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image Banner", name: "banner", widget:"image", require:"false"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image", require:"false"}
      - {label: "Description", name: "description", widget:"string"}
      - {label: "Porteurs", name: "porteurs", widget:"list"}
      - {label: "Documentation", name: "documentation", require:"false", widget: list, fields: [
          {label: "Nom", name: "name", widget: "string"},
          {label: "Lien", name: "link", widget: "string"}]}
  - name: "agenda" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Agenda" # Used in the UI, ie.: "New Post"
    folder: "site/content/agenda" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Node", name: "node", widget: "list"}
      - {label: "Tags", name: "tags", widget: list, require:"false", default: ['term_1', 'term_2']}
      - {label: "Porteurs", name: "porteurs", widget:"list", require:"false"}
      - {label: "Lieu", name: "location", widget: "string", require:"false"}
      - {label: "Journee Entiere", name: "fullday", widget: "boolean", default:"false"}
      - {label: "Recurrence", name: "recurring", require:"false", widget: list, fields: [
          {label: "Frequence", name: "frequency", widget: "list", options: ["DAILY", "WEEKLY", "MONTHLY"]},
          {label: "Combien", name: "count", widget: "string"},
          {label: "Fin", name: "link", widget: "string"}]}
      - {label: "Quand", name: "start", widget: "datetime"}
      - {label: "Fin", name: "end", widget: "datetime"}
      - {label: "Tarif", name: "tarif", widget: "string", require:"false", default: 'adhesion a la myne, 2e/an'}
      - {label: "Image Banner", name: "banner", widget:"image", require:"false"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image", require:"false"}
      - {label: "Description", name: "description", widget: "string", require:"false"}
      - {label: "Body", name: "body", widget: "markdown", require:"false"}
      - {label: "Documentation", name: "documentation", require:"false", widget: list, fields: [
          {label: "Nom", name: "name", widget: "string"},
          {label: "Lien", name: "link", widget: "string"}]}
      - {label: "Ressources", name: "ressources", require:"false", widget: list, fields: [
          {label: "Nom", name: "name", widget: "string"},
          {label: "Lien", name: "link", widget: "string"}]}
  - name: "ressources" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Ressources et Documentation" # Used in the UI, ie.: "New Post"
    folder: "site/content/documentation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Tags", name: "tags", widget: list, require:"false", default: ['term_1', 'term_2']}
      - {label: "Alias", name: "alias", widget: "string", require:"false"}
      - {label: "shortId", name: "shortid", widget: "string", require:"false"}
      - {label: "Model", name: "model", widget: "list", require:"false"}
      - {label: "Node", name: "node", widget: "list"}
  - name: "people" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "MYNOIS-E" # Used in the UI, ie.: "New Post"
    folder: "site/content/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "Tags", name: "tags", widget: list, default: ['term_1', 'term_2'], require:"false"}
      - {label: "Social", name: "social", widget: list, require:"false", fields: [
          {label: "Reseau", name: "name", widget: "string"},
          {label: "Lien", name: "link", widget: "string"}]}
