backend:
  name: git-giteway
#  repo: La-MYNE/Website/
#  branch: develop # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "static/img/" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "content/project" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Tags", name: "tags", widget:"markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image Banner", name: "banner", widget:"image"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget:"string"}
      - name: porteurs
        label: Porteurs du Projet
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
      - name: documentation
        label: Documentation
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
      - name: ressources
        label: Ressources
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}

  - name: "ateliers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Ateliers" # Used in the UI, ie.: "New Post"
    folder: "content/ateliers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Categories", name: categories, widget: list}
      - {label: "Tags", name: tags, widget: list, default: ['term_1', 'term_2']}
      - {label: "Tarif", name: "tarif", widget: "string"}
      - {label: "Image Banner", name: "banner", widget:"image"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Parent", name: "parent", widget: "string"}
      - {label: "Recurrent", name: "recurring", widget: "string"}
      - {label: "Recurrence", name: "recurrence", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: porteurs
        label: Animateurs
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
      - name: documentation
        label: Documentation
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
      - name: ressources
        label: Ressources
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}

  - name: "evenements" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Evenements" # Used in the UI, ie.: "New Post"
    folder: "content/agenda" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: Categories, name: categories, widget: list}
      - {label: Tags, name: tags, widget: list, default: ['term_1', 'term_2']}
      - {label: Lieu, name: lieu, widget: "string"}
      - {label: "Quand", name: "start", widget: "datetime"}
      - {label: "Fin", name: "end", widget: "datetime"}
      - {label: "Tarif", name: "tarif", widget: "string"}
      - {label: "Image Banner", name: "banner", widget:"image"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Parent", name: "parent", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: porteurs
        label: Animateurs
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
      - name: documentation
        label: Documentation
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
      - name: ressources
        label: Ressources
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
